### ISSUE TITLE
Blurry

### ISSUE THREAD

**Issue by NealSavage** [HyperPigeon/PolaroidCamera#2]
The pictures are insanely blurry. Any way to make it more clear?

**Comment by HyperPigeon** [comment]
This mod is sort of a salvage attempt of another mod I was making that was supposed to produce clear images that players could post on walls. However, there were some technical issues with the mod that I could never quite figure out, so I ended up re-using a lot of that code for this mod. I fully plan on re-visiting the original idea in the future once I get a bit more experience with dynamic rendering.
