### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by itsdinkd** [HyperPigeon/PolaroidCamera#3]
Dedicated server instance, 1.1,8.2, 10 players. Everytime it is used, the logs below happens.

https://spark.lucko.me/VGNQ3pRLA4 

![image](https://user-images.githubusercontent.com/35115304/168380723-cda7254a-f66d-4d5f-967b-ae865ccfcca9.png)

**Comment by HyperPigeon** [comment]
I've pushed an update that should hopefully alleviate the performance issues: https://modrinth.com/mod/polaroidcamera/version/v1.2.5. 

Please let me know if it works.

**Comment by HyperPigeon** [comment]
fixed in latest release (hopefully)
