### ISSUE TITLE
Photo taken in Nether are blank are Overworld (and vice-versa)

### ISSUE THREAD

**Issue by Dinrae** [HyperPigeon/PolaroidCamera#8]
As in title, using 1.4.0, if i take a photo in Nether, it is blank in Overworld, and visible again if i step up in Nether.
Too bad, i was pretty hyped about his mode.

**Comment by HyperPigeon** [comment]
I was unable to replicate the bug, as shown in the images below. 

![image](https://user-images.githubusercontent.com/58276133/212489779-cb1e1df8-2e34-4e8c-8ac7-d396e0d4a88c.png)

![image](https://user-images.githubusercontent.com/58276133/212489813-bb776e78-7591-44f0-83e4-2b2ae2c11bf8.png)
